name: Publish Nuget Package
on:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup dotnet Runtime
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Pack and Push Nuget Package
        run: |
          dotnet restore
          export PACKAGE_VERSION=${GITHUB_REF##*/}
          PACKAGE_VERSION=${PACKAGE_VERSION#?}
          dotnet pack ApiContracts.csproj -p:Version=${PACKAGE_VERSION} -p:RepositoryUrl="https://github.com/ajameslarner/ApiContracts"  -o .
          dotnet nuget push ApiContracts.${PACKAGE_VERSION}.nupkg -k ${NUGET_API_KEY} -s https://api.nuget.org/v3/index.json

# dotnet test YourTestProject.csproj -c Release
